sudo: required
language: python
python:
  - "2.7"
  - "3.6"

# command to install dependencies
install:
  - curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.2/install.sh | bash
  - nvm install node
  - python setup.py install
  - pip install coveralls
  - cd src/app/reactjs && npm install

# command to run tests
script:
  - npm run test
  - cd ../../../ && python setup.py test



after_success:
  - coveralls
